version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  auth_service:
    build:
      context: ./auth_service
      dockerfile: ./Dockerfile
    container_name: auth_service
    ports:
      - "8003:8003"
    environment:
      DB_HOST: auth_db
      DB_PORT: 5432
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    env_file:
      - .env  # подключает переменные из файла .env
    volumes:
      - ./auth_service:/app
    depends_on:
      auth_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - app-network


  auth_db:
    image: postgres:15.3
    container_name: auth_db
    environment:
      POSTGRES_DB: AuthDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - app-network

  post_service:
    build:
      context: ./post_service
      dockerfile: ./Dockerfile
    container_name: post_service
    ports:
      - "8006:8006"
    env_file:
      - .env
    environment:
      DB_HOST: post_db
      DB_PORT: 5432
    volumes:
      - ./post_service:/app
    depends_on:
      post_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8006/health"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - app-network

  post_db:
    image: postgres:15.3
    container_name: post_db
    environment:
      POSTGRES_DB: PostDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - post_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - app-network

  subscription_service:
    build:
      context: ./subscription_service
      dockerfile: ./Dockerfile
    container_name: subscription_service
    ports:
      - "8007:8007"
    env_file:
      - .env
    environment:
      DB_HOST: subscription_db
      DB_PORT: 5432
      SUBSCRIPTION_DB_URL: postgresql+asyncpg://postgres:postgres@subscription_db:5432/SubscriptionDB
      AUTH_SERVICE_URL: http://auth_service:8003
      POST_SERVICE_URL: ${POST_DB_URL}
      JWT_SECRET: ${JWT_SECRET}
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      DEBUG: True
    volumes:
      - ./subscription_service:/app
    depends_on:
      subscription_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      auth_service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8007"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - app-network

  subscription_db:
    image: postgres:15.3
    container_name: subscription_db
    environment:
      POSTGRES_DB: SubscriptionDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - subscription_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - app-network

  admin_service:
    build:
      context: ./admin_service
      dockerfile: ./Dockerfile
    container_name: admin_service
    ports:
      - "8009:8009"
    env_file:
      - .env
    environment:
      DB_HOST: admin_db
      DB_PORT: 5432
      DB_NAME: AdminDB
      DB_USER: postgres
      DB_PASSWORD: postgres
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      POST_SERVICE_URL: http://post_service:8006
      AUTH_SERVICE_URL: http://auth_service:8003
      SUBSCRIPTION_SERVICE_URL: http://subscription_service:8007
    volumes:
      - ./admin_service:/app
    depends_on:
      admin_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8009/health"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - app-network

  admin_db:
    image: postgres:15.3
    container_name: admin_db
    environment:
      POSTGRES_DB: AdminDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"
    volumes:
      - admin_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      auth_service:
        condition: service_healthy
      post_service:
        condition: service_healthy
      subscription_service:
        condition: service_healthy
      admin_service:
        condition: service_healthy
    healthcheck:
      # Лучше указать реальный путь, который точно существует
      test: ["CMD", "curl", "-f", "http://localhost/auth/health"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - app-network


volumes:
  auth_db_data:
  admin_db_data:
  post_db_data:
  subscription_db_data:
  rabbitmq_data:
  minio_data:

networks:
  app-network:
    driver: bridge






